### ISSUE TITLE
Simple nullables (int? MyEnum?) throws in .NET Core when settingKey: null

### ISSUE THREAD

**Issue by wachulski** [PolarbearDK/Miracle.Settings#2]
Repro changeset in: #1

.NET Core only, because of this piece: `ConfigurationValueProvider.cs`

```
public bool TryGetValue(string key, out string value)
		{
			value = _configurationRoot[key];
			return value != null;
		}
```

For `settingKey: null` in JSON config `_configurationRoot[key];` returns `""`

It works in .NET Framework:

![image](https://user-images.githubusercontent.com/1669844/73252119-82a81f00-41ba-11ea-97ec-e6cda1373f8c.png)

If I change the setting entry to: `settingKey: ""` it throws the same error.

**Comment by PolarbearDK** [comment]
This is odd behaviour
Apparently Microsoft.Extensions.Configuration.ConfigurationProvider behaves like this:

if you call configuration["Foo"]

Then it returns "" for { "Foo": null }
But it returns null for { } (property is not present).

Bug is in Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser:
... = data.ToString((IFormatProvider) CultureInfo.InvariantCulture);

My suggestion is to remove property from json.

**Comment by wachulski** [comment]
w.r.t. MS parsing bug: probably it's by design (nulls are prohibited as far as I understand): https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#values

**Comment by PolarbearDK** [comment]
Possible workaround is to ignore the returned "" by applying:
`        [Setting(IgnoreValue = "")]`
To each property.

**Comment by wachulski** [comment]
workaround acceptable
