### ISSUE TITLE
Nullable<MyEnum> fails to load the value

### ISSUE THREAD

**Issue by wachulski** [PolarbearDK/Miracle.Settings#3]
Related to #2 . See the initial investigation done there.

All target frameworks are impacted.

Here is the line I stepped into:

![image](https://user-images.githubusercontent.com/1669844/73264576-6bc1f680-41d3-11ea-988f-da7a6d6089ae.png)

`.IsEnum` is evaluated to false for nullable enums.

**Comment by PolarbearDK** [comment]
As a Workaround, Remove Nullable<> and add DefaultValue to property.

**Comment by PolarbearDK** [comment]
This should be fixed in 3.0.5
