### ISSUE TITLE
Can I load settings from a dictonary?

### ISSUE THREAD

**Issue by Martin-Andersen** [PolarbearDK/Miracle.Settings#4]
Hi I would like to load setting from a database, are there a way to load data from a dictionary or list of objects.
I would like to take advantages of the type safe loading you have build

**Comment by PolarbearDK** [comment]
Hi Martin,

There are already examples of that in the unit tests.
See [SampleSqlValueProvider.cs](https://github.com/PolarbearDK/Miracle.Settings/blob/1b60753078c11b5a245e717876cfb762f8b826a9/Source/Miracle.Settings.Tests/DatabaseTest/SampleSqlValueProvider.cs)

There is also a dictionary value provider you can use:
[DictionaryValueProvider.cs](https://github.com/PolarbearDK/Miracle.Settings/blob/1b60753078c11b5a245e717876cfb762f8b826a9/Source/Miracle.Settings/ValueProviders/DictionaryValueProvider.cs)

Third option is to write your own value provider
